version: '3.8'

services:
  
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: mugisha146/newbookrental:latest  # Set the desired image name here
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Exposing port 443 for HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static  # Serve static files via Nginx
      - ./media:/media    # Serve media files via Nginx
      - ./certs:/etc/nginx/ssl  # SSL Certificates volume
    depends_on:
      - web

volumes:
  pgdata:
